### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by whizkydee** [kosyfrances/calculator#1]
Hi @andela-kanyanwu ,

Nice work. But I strongly believe the UI can be improved and some tweaks can be made. I can help you out.

**Comment by kosyfrances** [comment]
Hi @whizkydee, thanks. Feel free to help out and submit a pull request. That was my first programming project :)

**Comment by whizkydee** [comment]
@andela-kanyanwu Yeah, i'll do so.
